### ISSUE TITLE
Error occurs when sell percentage100 on pump.fun

### ISSUE THREAD

**Issue by RomanticBarracks** [outsmartchad/solana-trading-cli#16]
![image](https://github.com/user-attachments/assets/b17404d5-f789-4597-b04b-9efdbd587ecd)

This erros occurs when sell 100 on pump fun

**Comment by MichaelFedorov** [comment]
`let sellResults = await sdk.sell(
      wallet,
      mintPubKey,
      BigInt(
        Math.round(currentTokenBalance * Math.pow(10, DEFAULT_DECIMALS) * sellPercentage)
      ),
      SLIPPAGE_BASIS_POINTS,
      {
        unitLimit: 250000,
        unitPrice: 250000,
      }
    );`


I added  Math.round and it works for me
