### ISSUE TITLE
help boost volume( SolanaJSONRPCError: failed to get token account balance: Invalid param: could not find account

### ISSUE THREAD

**Issue by lonely1215225** [outsmartchad/solana-trading-cli#18]
![QQ_1723015180326](https://github.com/user-attachments/assets/adde9221-b638-48aa-8afb-9ed7aeccf9be)

**Comment by lonely1215225** [comment]
when sell and then getSPLTokenBalance
![QQ_1723015216970](https://github.com/user-attachments/assets/09303ccd-852c-4394-b57d-040c276c90c8)

**Comment by outsmartchad** [comment]
before running the script, make sure you have the token and some wsol for swapping, token account not found means you don't have the token in your wallet
