### ISSUE TITLE
2024/08/23 09:58:03 UTC Raydium_Api sdk logger error GET https://api-v3.raydium.io/pools/info/mint?mint1=99myne1mVnsSv2kAkzZDfNnwf5Xb4SASJnaCRXdbpump&mint2=So11111111111111111111111111111111111111112&poolType=all&poolSortField=default&sortType=desc&pageSize=100&page=1 403 AxiosError: Request failed with status code 403

### ISSUE THREAD

**Issue by lonely1215225** [outsmartchad/solana-trading-cli#21]
2024/08/23 09:58:03 UTC Raydium_Api sdk logger error GET https://api-v3.raydium.io/pools/info/mint?mint1=99myne1mVnsSv2kAkzZDfNnwf5Xb4SASJnaCRXdbpump&mint2=So11111111111111111111111111111111111111112&poolType=all&poolSortField=default&sortType=desc&pageSize=100&page=1 403
AxiosError: Request failed with status code 403

when run boost_volume.js

**Comment by outsmartchad** [comment]
i'm converting all the .js script to .ts, you could try it later

**Comment by lonely1215225** [comment]
> i'm converting all the .js script to .ts, you could try it later

nice work ! thanks!
