### ISSUE TITLE
I feel like there should be a process to create a associated token account, otherwise you won’t be able to buy new tokens

### ISSUE THREAD

**Issue by lonely1215225** [outsmartchad/solana-trading-cli#22]
![image](https://github.com/user-attachments/assets/c6a0d99d-7424-435a-b441-0ae31c7ef7d9)

here

**Comment by outsmartchad** [comment]
let me check again

**Comment by outsmartchad** [comment]
<img width="529" alt="image" src="https://github.com/user-attachments/assets/c80324d4-99b6-4e84-aa17-42c03b62ed8a">
have inserted a create ata instruction when buying the token, should be good
