### ISSUE TITLE
Application hanging in buy/sell/swap on this (fixed)

### ISSUE THREAD

**Issue by EverydayEnder** [outsmartchad/solana-trading-cli#4]
Application hanging in buy/sell/swap on this:

Jito Fee: 0.00009 sol
Sending tx to Jito validators...
Jito validator accepted the tx
Confirming the jito transaction...

Any ideas?

**Comment by ManofDiligence** [comment]
Be sure that you got some Wrapped solana in your wallet for swapping!

**Comment by EverydayEnder** [comment]
You sir, are a legend!!

that worked. Last issue is using the boost_volume.. i am getting stuck here:
Transaction executed. Confirming transaction...

Any ideas?

**Comment by ManofDiligence** [comment]
try to increase the slippage, or the computeunit, your token might be too high slippage

**Comment by ManofDiligence** [comment]
You can adjust it in the swap function of this https://github.com/ManofDiligence/solana-memecoin-cli/blob/main/src/Pool/swap.js

**Comment by ManofDiligence** [comment]
will make a command for boost volume and other functions, but we hope that someone who are interested could contribute to the project as well!

**Comment by EverydayEnder** [comment]
Thanks for pointing out the gas and compute units. i was wondering why gas was 50 cents lol.

So the buy and sell functions work perfect on their own. When i do the boost_volume module, it fails to produce a valid signature. I added a little logging and it gives this:

Transaction failed to produce a valid signature.

And solscan gives the error "Program error: "Instruction #4 failed - invalidinput

I would be happy to help! Or at least try. Albeit i am nowhere near as talented as you. I am early still on my dev path. But i can sure try. tbh i use ai for almost all of my coding cause i am not good yet. Once i get the volume part working, my next step was to integrate it into a telegram bot.

**Comment by ManofDiligence** [comment]
for now, what the function do is submit the sell and buy at the same time(same tx), so it's not be determined which instruction do first, if sell do first, it checks if the wallet has that token already, if buy first, then it's fine since you already got wsol, if you develop a bot, i would be happy to help!

**Comment by ManofDiligence** [comment]
so, the thing is make sure you have some token that the value equal to the sol per order!

**Comment by ManofDiligence** [comment]
the function is legit af, 0.5 per order generate 30k volume in just few hours!

**Comment by EverydayEnder** [comment]
Ok that makes sense! once i did the buy some of that token, then volume_booster started to work. Still saying failed to get valid signature, but it is working. Also it runs a few times then gets stuck here:

Executing transaction...
Transaction executed. Confirming transaction...


Still trying to work out why it hangs then stops. I will try to add some logic to restart the volume if it hangs if you have no ideas what i could be doing wrong.

It is legit man! this whole thing is amazing. Thank you for doing this. I know most people sell volume bots or lease for tons of money. You are a real chad

**Comment by ManofDiligence** [comment]
Try to increase the priority fee or jito tips and run again.

**Comment by ManofDiligence** [comment]
I Believe one thing, you give the most, and you will earn more, I am doing it for free for anyone to use it!

**Comment by EverydayEnder** [comment]
Yes man that is absolutely true. Thank you for what you do.

I tried upping those and still nothing. When it hangs, here is the result of the values. I added logging to debug:

swapForVolume result: confirmed=true, signature=undefined

So for whatever reason, it is expecting a sig to be returned but it is coming back as undefined. I will keep digging :)

**Comment by ManofDiligence** [comment]
could you directly send me a email (ur tx in solscan), i am willing to help u with that

**Comment by ManofDiligence** [comment]
And it is not every swap tx can be successfully land on Solana, what we can do is increase the success rate of it by add fee and jito bundle,

**Comment by ManofDiligence** [comment]
@EverydayEnder hey, please see the latest commit. recommend you to choose the closest endpoint to ur location!

**Comment by EverydayEnder** [comment]
Amazing man! thanks for that. I will update my copy when i get home tonight! And i will send results.

**Comment by EverydayEnder** [comment]
> @EverydayEnder hey, please see the latest commit. recommend you to choose the closest endpoint to ur location!

What do you mean by this? Where do i choose that?

**Comment by outsmartchad** [comment]
@EverydayEnder, these Jito endpoints, https://github.com/outsmartchad/solana-memecoin-cli/blob/main/src/Transactions/jito_tips_tx_executor.js
